UDP_IP_HUB="127.0.0.1"
UDP_PORT_HUB_IN=7100
UDP_PORT_HUB_RESPONSE=6100
HUB_NET=(UDP_IP_HUB, UDP_PORT_HUB_IN)

UDP_IP_NEW_TOKEN="127.0.0.1"
UDP_PORT_NEW_TOKEN_IN=7300
UDP_PORT_NEW_TOKEN_RESPONSE=6300
NEW_TOKEN_NET=(UDP_IP_NEW_TOKEN, UDP_PORT_NEW_TOKEN_IN)

UDP_IP_ACTION_MANAGER="127.0.0.1"
UDP_PORT_ACTION_MANAGER_IN=7400
UDP_PORT_ACTION_MANAGER_RESPONSE=6400
ACTION_MANAGER_NET=(UDP_IP_ACTION_MANAGER, UDP_PORT_ACTION_MANAGER_IN)

UDP_IP_STATE_MANAGER="127.0.0.1"
UDP_PORT_STATE_MANAGER_IN=7500
UDP_PORT_STATE_MANAGER_RESPONSE=6500
STATE_MANAGER_NET=(UDP_IP_STATE_MANAGER, UDP_PORT_STATE_MANAGER_IN)

UDP_IP_CLOCK="127.0.0.1"
UDP_PORT_CLOCK_IN=7000
UDP_PORT_CLOCK_RESPONSE=6000
CLOCK_NET=(UDP_IP_CLOCK, UDP_PORT_CLOCK_IN)

UDP_IP_SHORT_MEM="127.0.0.1"
UDP_PORT_SHORT_MEM_IN=7201
UDP_PORT_SHORT_MEM_RESPONSE=6201
SHORT_MEM_NET=(UDP_IP_SHORT_MEM, UDP_PORT_SHORT_MEM_IN)

UDP_IP_DB="127.0.0.1"
UDP_PORT_DB_IN=7200
UDP_PORT_DB_RESPONSE=6200
DB_NET=(UDP_IP_DB, UDP_PORT_DB_IN)

UDP_IP_LOG="127.0.0.1"
UDP_PORT_LOG_IN=9999
LOG_NET=(UDP_IP_LOG, UDP_PORT_LOG_IN)

UDP_IP_ENVIRONMENT="127.0.0.1"
UDP_PORT_ENVIRONMENT_IN=9998
ENVIRONMENT_NET=(UDP_IP_ENVIRONMENT, UDP_PORT_ENVIRONMENT_IN)

UDP_IP_TRL_PROCESS="127.0.0.1"
UDP_PORT_TRL_PROCESS=9997
TRL_PROCESS_NET=(UDP_IP_TRL_PROCESS, UDP_PORT_TRL_PROCESS)

def request_one(osock, to, msg):
	osock.sendto(msg, to)
	data, addr = osock.recvfrom(1024)
	return data.rstrip()

def request(osock, to, msg):
	osock.sendto(msg, to)
	data, addr = osock.recvfrom(1024)
	results = []
	while data != '.':
		results.append(data)
		data, addr = osock.recvfrom(1024)

	return results